### ISSUE TITLE
🐛 BUG: "Last Year" is split in two lines

### ISSUE THREAD

**Issue by iamludal** [dailydotdev/daily#373] opened 2021-12-05 11:42 UTC
### What went wrong? 🤔

The "Last Year" option in the profile page is split in two lines.

![image](https://user-images.githubusercontent.com/44783088/144744854-64c2f7e1-2bb7-40da-9aec-8be4ac844758.png)

### Expected Behavior

It should either be on one line, or the background height should be adjusted to match the box size.

### Actual Behavior

The option is currently split in two lines

### Steps to Reproduce Issue

Navigate to your profile and select the "Last Year" option from the "Articles Read" section.

### Solution

Something like `white-space: nowrap` ?

#### Operating System

Linux (Ubuntu 21.04)

#### Version of Daily

3.10.3

#### Browser

Google Chrome 96.0.4664.45

**Comment by idoshamun** [comment] 2021-12-06 06:07
Thanks a lot for reporting!
We will go ahead and fix it :)

**Comment by sshanzel** [comment] 2021-12-06 10:20
Hi @iamludal, thank you so much for reporting this concern! We have merged the changes and the fix should have been reflected by now.

Please let us know if the issue still persists so we can take further action.

**Closed by sshanzel** 2021-12-06 10:20 UTC
Labels: Type: Bug

**Comment by iamludal** [comment] 2021-12-06 11:00
You're most welcome! 🤗

**Comment by iamludal** [comment] 2021-12-06 11:04
Well, I was expecting to see the full text ("Last year") instead. Was it on purpose? 🤔
![image](https://user-images.githubusercontent.com/44783088/144835257-c9a53f42-99d4-49ef-b646-1a878942aa75.png)

**Comment by sshanzel** [comment] 2021-12-06 11:18
Thank you for the very quick response. May I know what is the system font you are using? So I could replicate the case better.

**Comment by iamludal** [comment] 2021-12-06 13:20
Well I don't know, I think it's the default font of my browser. Still, my system font is "Ubuntu Regular", but I don't think it has something with it.

However, it seems like the `truncate` class is causing the issue (because it has a `overflow: hidden` property). I tried to disable it, and it works as expected. The only thing is that the right arrow is shifted to the right, but the background doesn't adjust accordingly (to fix this, you can remove the `w-full` class on the parent button, which seems unlock the button width).

Don't hesitate if you need more information. :)

**Comment by sshanzel** [comment] 2021-12-06 13:40
@iamludal we really do appreciate it when awesome people like **you** are providing as much information as they could.

The reason I had to ask was the fact we use `system-ui` for our font which utilizes the browser's current font which uses the font of the OS.

In this case, the cutting off of the content is our expected behavior based on our UI guideline. This means we will have to make adjustments to the actual `width`.

After further checking, I noticed a static value on its `width` which should not be the case to allow responsiveness with its content.

**Comment by iamludal** [comment] 2021-12-06 15:23
My pleasure! I really enjoy your app.

Thanks for this information. Don't hesitate to keep me informed when you have some news.

**Comment by sshanzel** [comment] 2021-12-07 11:40
We are very glad to hear you are enjoying the app! Each and everyone in the team is always 100% working to improve the community's experience every moment.

We have now merged the fix which should have tackled the primary concern in this issue. Hopefully, it is displaying as intended on your end now.

Thank you so much for your patience! 🙏

**Comment by iamludal** [comment] 2021-12-07 13:27
It works as expected, congratulations! 😎

![image](https://user-images.githubusercontent.com/44783088/145037525-cf506fb5-5be8-4cc2-a961-c3fe101e647d.png)
