### ISSUE TITLE
🐛 BUG: Hyperactive error

### ISSUE THREAD

**Issue by richardhovdsveen** [dailydotdev/daily#1546] opened 2024-10-28 11:53 UTC
### What went wrong? 🤔

Hi team,

When adding a link, the "Add Link" window behaves erratically when the "https" error message appears. The window bounces excessively, making it difficult to interact with or read the error message.

I've attached a video for reference.

Thank you!

https://spamassp-my.sharepoint.com/:v:/g/personal/richard_hovdsveen_prokom_no/EZ3GDzZDT7RJi9SOyg4NG4oBKM6x7WNNtgA_5cmlzZRpUw?e=tIKGfu

### Expected Behavior

Error appear on error, and removes when fixed

### Steps to Reproduce Issue

```bash
1. Go to 'add shortcut'
2. add url without https
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-10-29 12:12
Hi @richardhovdsveen,

Thanks for reporting. I think we have a PR pending to fix this or at least an open issue. @sshanzel am I right?

**Comment by sshanzel** [comment] 2024-10-29 18:15
> Hi @richardhovdsveen,
> 
> Thanks for reporting. I think we have a PR pending to fix this or at least an open issue. @sshanzel am I right?

Yes, we have an open PR that will fix this issue, and it is already at its later stage. We hope to merge it soon 🙏

**Comment by rebelchris** [comment] 2024-10-29 18:40
Duplicate of: https://github.com/dailydotdev/daily/issues/1466
Closing this one.

**Closed by rebelchris** 2024-10-29 18:40 UTC
Labels: Type: Bug
