### ISSUE TITLE
🐛 BUG: Squad drop down flickering

### ISSUE THREAD

**Issue by avi12** [dailydotdev/daily#1541] opened 2024-10-25 04:02 UTC
### What went wrong? 🤔

https://github.com/user-attachments/assets/e191fc11-7b3f-4c49-bb7b-4f95ff8822da

### Environment

Website

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-10-27 08:00
Hi @avi12,

Thanks for the report!

**Comment by n-d-r-d-g** [comment] 2024-10-29 16:26
I've been able to reproduce this bug in other dropdowns as well (at `/account/notifications`). The issue seems to come from the `Menu` component from `@dailydotdev/react-contexify`.

**Comment by rebelchris** [comment] 2024-10-29 18:41
Duplicate of: https://github.com/dailydotdev/daily/issues/1466
It's a global issue, we're working on a fix.

**Closed by rebelchris** 2024-10-29 18:41 UTC
Labels: Type: Bug
