### ISSUE TITLE
🐛 BUG: Add tags from search not working

### ISSUE THREAD

**Issue by msayed-net** [dailydotdev/daily#163] opened 2020-06-16 22:13 UTC
### What went wrong? 🤔

Trying to add tags from search like "flutter", nothing happens

### Expected Behavior

to be added

### Actual Behavior

reload content area with no change and not added to my tags

### Steps to Reproduce Issue

it's up to you

### Solution

it's up to you

### Environment

Mozilla Firefox (Desktop)

#### Operating System

MacOS

#### Version of Daily

2.15.6

**Comment by idoshamun** [comment] 2020-06-18 14:39
Hi @msayed-net!

Thanks for reporting this bug, I was able to reproduce this issue.
I will work on a fix and let you know once it's done :)

**Comment by idoshamun** [comment] 2020-06-22 13:55
The issue is now fixed and will be released in the upcoming version

**Closed** 2020-06-22 13:54 UTC
Labels: Priority: High, Status: Accepted, Status: In Progress, Type: Bug

**Comment by msayed-net** [comment] 2020-06-22 14:58
Excellent, Thank you
