### ISSUE TITLE
🐛 BUG:  Use Google Translate, the page will crash after a period of time

### ISSUE THREAD

**Issue by AREA-CQK** [dailydotdev/daily#1446] opened 2024-09-20 00:48 UTC
### What went wrong? 🤔

Every time I use Google Translate, after translating the page, it crashes after a short period of time

### Expected Behavior

Hope to have normal access

### Steps to Reproduce Issue

```bash
1. open daily.dev Tab
2. Right click menu and select Google Translate
3. Use for a while
4. See the error： Application error: A client exception occurred (see browser console for more information).
```

### Environment

macos 14.16.1

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-09-29 11:23
Hi @AREA-CQK,

Is it caused by scrolling or even just leaving the page open?

**Comment by sparshcodes** [comment] 2024-10-20 17:19
@idoshamun @sshanzel 
can i take this issue?
it is happening on scrolling, i guess most probably when the network requests are happening.

**Comment by sshanzel** [comment] 2024-10-23 18:27
@sparshcodes feel free to take a peek, but we don't normally spend effort if the issue is triggered by a 3rd party app/service.

**Comment by kenshanta** [comment] 2024-11-21 10:03
> @sparshcodes feel free to take a peek, but we don't recommend it since, normally, we don't spend effort if the issue is triggered by a 3rd party app/service.

So what's the optimal approach for someone who would like to subscribe and isn't familiar with the English language?

**Comment by rebelchris** [comment] 2024-12-03 06:48
Hi @kenshanta ,

We actually added support to translate post titles recently.
It's not a fully blown translation service but atleast you can quicker read titles on your feed.
https://docs.daily.dev/docs/setting-up-your-feed/advanced-filtering-options#content-and-language-filtering

Hoping this helps a bit, closing this issue for now as we can't solve third party issues.

**Closed by rebelchris** 2024-12-03 06:48 UTC
Labels: Type: Bug
