### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by quostta** [dailydotdev/daily#161] opened 2020-06-13 01:11 UTC
### What went wrong? 🤔

List of sources and tags that can be curated on left side of a new tab resets after a reload or whenever a new tab is opened.

### Expected Behavior

The removed sources and tags should remain removed and Daily should show stories/news from sources and tags that are selected by the user. 

### Actual Behavior

The sources and tags list is reset after each reload or on new tab open.

### Steps to Reproduce Issue

1. Hover to the left most of a new Daily tab page.
2. The sidebar expands with list of every source available on Daily
3. Hover over one source. When the 'x' on its right appears, click it. That source is now removed.
4. Wait a while & reload the page or open a new tab.
5. The source previously removed is now back in the list.

The same thing also occurs but for tags. Add new tags to the list and after a reload it disappears.

![Screen Shot 2020-06-12 at 20 01 29](https://user-images.githubusercontent.com/55330600/84556486-a9d63780-ace8-11ea-8f38-09738c348461.png)

### What's even worse?

It doesn't work when signed in with GitHub either.

#### Operating System

Windows 10

#### Version of Daily

Version 2.15.5

#### Browser

Firefox for Windows PC

**Comment by idoshamun** [comment] 2020-06-13 06:34
Hi @quostta,

Thank you for reporting this critical issue.
I will try to see if I can reproduce this issue and hopefully fix it as soon as possible.

By the way, by the look of your screenshot, it seems that you are not properly logged-in because of your profile image. Could you try to logout and login again?

**Comment by idoshamun** [comment] 2020-06-14 14:10
I didn't manage to reproduce this issue.
Could you please update to the latest version 2.15.6 and let me know if it still happens?

**Comment by quostta** [comment] 2020-06-15 20:28
I have tried to logout and login after but my profile picture doesn't show up. That could be a bug within itself. And I use Firefox and there are no new updates in the extensions page for Daily. Still on 2.15.5

**Comment by quostta** [comment] 2020-06-15 20:29
This bug shouldn't exist even if a user is logged out. I logged in to see if the bug exists but I prefer to use Daily while logged out.

**Comment by idoshamun** [comment] 2020-06-16 05:16
I tested both scenarios and they work pretty well. I guess you were trapped in some unknown bug.
I'm closing the issue, for the time being, thank you for the effort :)

**Closed by idoshamun** 2020-06-16 05:16 UTC
Labels: Status: On Hold, Type: Bug
