### ISSUE TITLE
🐛 BUG: Search bar only gets LLM results and doesn't return articles

### ISSUE THREAD

**Issue by mickeymaddula** [dailydotdev/daily#982] opened 2023-09-25 19:09 UTC
### What went wrong? 🤔

With the newly released version of search that uses LLM & AI to generate results for questions. The true search functionality that existed before where users could search through the recommended or available articles throughout daily.dev. 

For example, searching for "eslint" returns what eslint is and explaining things rather than recently observed or shown articles:

### Expected Behavior

The search must show results for the articles that match the search query along with suggested LLM-based recommendations.

### Steps to Reproduce Issue

```bash
1. Go to the Search box on the app with the new search bar.
2. Click on search and look up the keyword "javascript, agile, security.."
3. Observe results.
4. See the results only display LLM-based results.
```

### Solution Proposed

The search must show results for the articles that match the search query along with suggested LLM-based recommendations.

### Screenshots

![image](https://github.com/dailydotdev/daily/assets/15098263/891b4300-c66d-40c2-addd-01ef12d29b9b)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2023-09-26 06:19
Hi @mickeymaddula,

It's not a bug, it's a feature 😉 
Joking, we received this concern from several users and we're considering how to proceed at this point.

Best,
Ido

**Comment by Naveenchikka** [comment] 2023-10-11 07:20
Please consider adding back the search feature for articles in feed page. It really enhances users experience to find and go through the articles easily.

**Comment by rebelchris** [comment] 2023-10-11 07:23
Hi @mickeymaddula and @Naveenchikka we actually recently re-added the article search.
You should now have access to both types of search.

The article search is called `Post finder` and can be found [here](https://app.daily.dev/posts/finder).

Closing this for now.

**Closed by rebelchris** 2023-10-11 07:23 UTC
Labels: Type: Bug
