### ISSUE TITLE
🐛 BUG: Account and bookmarks not being synced on mobile

### ISSUE THREAD

**Issue by rodrigojmr** [dailydotdev/daily#205] opened 2020-10-24 20:43 UTC
On desktop I am logged in on daily.dev with my github account. When I try to use the Daily Go PWA, I log in using the same account, but nothing syncs. Bookmarks or posts in my feed. I've logged in and out in both.

#### Operating System
Mobile, Android 9

#### Version of Daily
Daily Go ver 3

**Comment by idoshamun** [comment] 2020-10-25 09:36
Thanks for reaching out 🙏
Let's try to investigate this together so I'll have information as I cannot understand the root cause at the moment.

When you're logged-in to the extension do you see your bookmarks?
If yes, try to log-out and check if the bookmarks are gone?
If yes, try to log-in again and check if they're back.

**Comment by rodrigojmr** [comment] 2020-10-25 10:41
When I opened the issue, I didn't check for a repository for Daily Go, which is the platform I'm having issues with, so apologies for that. Should I open an issue there? Here's more details on it:

For both desktop and mobile, I'm logging in with this github account.  

On desktop, when I'm logged in on desktop, I see my bookmarks. When I log out, the bookmarks are gone, and when I log back in, they are back.

On mobile, when I log in, I don't see any bookmarks. Daily Go tells me to get the extension, which I've been using for about a month+. When I log out, Daily Go just asks me to log back in, which I do, but no bookmarks or content is synced.

**Comment by idoshamun** [comment] 2020-10-25 13:27
First of all, it's great to hear that your account is not bugged or anything.
The bookmarks are synced with the extension and it's a good sign.
Probably it's something with daily go. daily go is in a maintenance phase and we're no longer working on it, and we'll probably take it down soon.
I'll try to give a look and see if I can resolve the issue.

**Comment by rodrigojmr** [comment] 2020-10-25 13:59
I see, I wasn't aware of that. Out of curiosity, I assume something for mobile may be being worked on? Thanks for checking it out!

**Comment by idoshamun** [comment] 2020-10-25 14:44
Yes indeed. We're building a new webapp that is partially live already.
It's mainly used for commenting and sharing posts today but we'll expand it over time.

**Comment by idoshamun** [comment] 2020-10-28 13:27
I think I fixed the issue.
Could you please confirm?

**Comment by rodrigojmr** [comment] 2020-10-29 10:55
The issue is still persisting on my end.

**Comment by idoshamun** [comment] 2020-10-29 21:29
Oh, that's weird. Don't you see at all your bookmarks in Daily Go?
Could you please try incognito?

**Comment by rodrigojmr** [comment] 2020-10-30 03:02
Yeah, I cleared chrome's data from github and go. daily.dev, and tried both in normal and incognito, and nothing was syncing. I also can't seem to actually bookmark any article.

Also, if it's deprecated and will be replaced, don't worry about it too much.

**Comment by idoshamun** [comment] 2020-11-02 06:52
I'm sorry to hear that it didn't solve the issue but thank you for your understanding!
I'll close the issue for the time being and hopefully, we will have a new solution soon.

**Closed by idoshamun** 2020-11-02 06:52 UTC
Labels: Priority: Low, Status: Accepted, Type: Bug
