### ISSUE TITLE
🐛 BUG: CPU usage spiked up on Windows

### ISSUE THREAD

**Issue by saqibameen** [dailydotdev/daily#162] opened 2020-06-15 09:31 UTC
### What went wrong? 🤔

On Windows, when Daily is enabled, the CPU usage spikes up. 

![screenshot](https://i.imgur.com/7vonCUE.png)

### Expected Behavior

Shouldn't be happening.

### Actual Behavior

CPU usage is spiked up as mentioned above.

### Steps to Reproduce Issue

I opened Chrome. The fan was turned on after a while. When I checked the task manager, I noticed chrome usage and on debugging I was able to fix this by disabling the Daily extension.

### Solution

NA

#### Operating System

Windows 10

#### Version of Daily

2.15.6

#### Browser

Chrome for Windows. 

### Extra Info

It's a 10th gen i7 processor with NVMe SSD & 16Gigs RAM. Ideally, it should be fine.

**Comment by idoshamun** [comment] 2020-06-16 05:34
Hi @saqibameen,

Thanks for reporting this important issue.
Can you share any specific use cases where it happens, or is it just random?

**Comment by saqibameen** [comment] 2020-06-16 06:38
@idoshamun 

It was random. I was only able to trace it via task manager. 

I might have access to this machine for some days. I'll be happy to share more info/use case, if I can find any.

**Comment by idoshamun** [comment] 2020-06-18 14:31
@saqibameen Thanks :)
Looking forward to the help of the community on this one.
If we have Windows users, it will be great to collaborate to solve it 😁

**Comment by TylerPottsDev** [comment] 2020-06-25 15:18
This also occurs on Chrome for my Macbook Pro 2015, MacOS Catalina (10.15.2).

**Comment by idoshamun** [comment] 2020-06-25 16:01
Thanks @TylerPottsDev for confirming it happens on MacOS as well.
If anyone has any clue let me know...
My hint is the masonry grid or the tons of images.

**Comment by sshanzel** [comment] 2020-07-18 10:36
I'm on Windows with i7 8th gen, NVMe SSD with 32GB RAM, and everything seems to be working fine on my end.

**Comment by idoshamun** [comment] 2020-07-18 11:39
I have a feeling of what may be the root cause for the spikes, we will introduce a UI change in the upcoming weeks that might solve this problem.

**Comment by idoshamun** [comment] 2020-09-30 07:16
With the latest UI changes, I would be happy if someone can confirm this issue still exists.
Until then, I close this issue.

**Closed by idoshamun** 2020-09-30 07:16 UTC
Labels: Status: Accepted, Status: Available, Type: Bug, help wanted
