### ISSUE TITLE
🐛 BUG: bug in the calendar

### ISSUE THREAD

**Issue by alerrandro1999** [dailydotdev/daily#882] opened 2023-04-27 12:12 UTC
### What went wrong? 🤔

the reading date on the calendar is one day behind.
if I read an article on the 27/04. the calendar shows 04/26

### Expected Behavior

the calendar was to show the correct day of reading the article

### Steps to Reproduce Issue

```bash
1. Go to 'https://app.daily.dev/profile'
2. Click on '....'
3. Scroll down to 'Posts read in the last year'
4. See the error
```

### Solution Proposed

NA

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 10,  Chrome 112.0.5615.138

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

10.1.2

### Additional Context

```bash
NA
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2023-04-27 14:16
Hi @alerrandro1999,

Thanks for the report. Can you please make sure the timezone is set correctly in your profile settings?
This may be the cause for such lag.

**Comment by alerrandro1999** [comment] 2023-04-27 17:10
> Hi @alerrandro1999,
> 
> Thanks for the report. Can you please make sure the timezone is set correctly in your profile settings? This may be the cause for such lag.

I changed the settings and the bug continued, tomorrow I'll see if it changes.

**Comment by alerrandro1999** [comment] 2023-04-28 12:03
> > Hi @alerrandro1999,
> > Thanks for the report. Can you please make sure the timezone is set correctly in your profile settings? This may be the cause for such lag.
> 
> I changed the settings and the bug continued, tomorrow I'll see if it changes.

the error still persists, for two articles and the date is like yesterday 04/27

**Comment by idoshamun** [comment] 2023-04-30 08:09
@sshanzel you're welcome to step-in and help @alerrandro1999 :)

**Comment by sshanzel** [comment] 2023-04-30 08:27
Hi @alerrandro1999! Sorry to hear you are having this issue. To provide an accurate assessment and solution for the issue, can you provide the information below?

- Your username/handle.
- The timezone where you are currently physically located (also if you are using any VPN). Just the country/state would do.
- The actual value in your settings for `timezone` in dailydev.

**Comment by bottercode** [comment] 2023-05-02 11:08
Can someone provide the video/screenshot of the bug ?

**Comment by alerrandro1999** [comment] 2023-05-02 11:38
> Oi@alerrandro1999! Lamentamos saber que você está tendo esse problema. Para fornecer uma solução precisa para o problema, você pode fornecer as informações abaixo?
> 
> * Seu nome de usuário/identificador.
> * O fuso horário onde você está fisicamente localizado (também se estiver usando qualquer VPN). Apenas o país/estado serviria.
> * O valor real em suas configurações `timezone`em dailydev.

alerrandro
Brasil/Pará
(UTC-3) Brasilia

**Comment by sshanzel** [comment] 2023-05-14 11:50
> Can someone provide the video/screenshot of the bug ?

Hi @bottercode we will investigate the concern and will let you know about it once we'll be able to reproduce the issue.

> alerrandro
Brasil/Pará
(UTC-3) Brasilia

@alerrandro1999 thanks for the additional info. We'll get back to you after doing our internal investigation.

**Comment by sshanzel** [comment] 2023-06-05 13:17
Hi @alerrandro1999, apologies for the time we have taken investigating. Unfortunately, we were not able to reproduce the issue with the configurations given and tried a few similar cases. With that, we have a known issue that could cause this concern and we have it in our roadmap to be fixed in the future. Once we get that released, we will come back and visit this case if it was somewhat related. Thank you for your patience 🙏

**Closed by sshanzel** 2023-06-05 13:17 UTC
Labels: Type: Bug
