### ISSUE TITLE
🐛 BUG: Time sync error

### ISSUE THREAD

**Issue by jreyesch** [dailydotdev/daily#1439] opened 2024-09-16 17:06 UTC
### What went wrong? 🤔

There is a time sync error with the streak counter. In my locality today is Monday but the tracker is one day behind. I read todays post but is marked for Sunday (yesterday).
Thanks.

![Screenshot from 2024-09-16 09-55-51](https://github.com/user-attachments/assets/87d68ffb-dd93-4381-b587-94d50243bcb6)

### Expected Behavior

The streak counter should be marked for the current date.

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Ubuntu 24.04, extension for Brave browser v169.168 and Android(14)  App

### Browsers

Brave

### OS

Linux

### Version of daily.dev

16

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by nensidosari** [comment] 2024-09-17 05:11
Hi @jreyesch,

Thank you for reporting this issue!

Before we move forward to investigate, could you please make sure you have the right timezone set in your profile (https://app.daily.dev/account/notifications)? 
This relates to how the streak updates, and not having that right might be the root cause of the issue you are facing.  

Please do check that and let us know if the issue still persists.

Best

**Comment by jreyesch** [comment] 2024-09-17 18:43
Hi, thanks for the reply.

I confirm my timezone is set correctly.

Thanks. Regards.

**Comment by rebelchris** [comment] 2024-11-04 07:18
Thanks for reporting both.
Could you send your user id in this thread:
https://github.com/dailydotdev/daily/issues/1439

Will close this one to keep all comms around streak issues in one place.
You can find your user id this way: 
https://api.daily.dev/id

**Closed by rebelchris** 2024-11-04 07:18 UTC
Labels: Type: Bug

**Comment by sec252** [comment] 2024-11-04 16:43
@rebelchris  What do you need my user id for?

**Comment by jreyesch** [comment] 2024-11-04 16:59
@rebelchris Hello.
I'm still seeing the bug, did I miss some configuration or extra needed step?

<img width="424" alt="Screenshot 2024-11-04 at 9 57 59 a m" src="https://github.com/user-attachments/assets/9b0e0e86-1ea7-40af-8d87-ba2697bacb4e">

**Comment by rebelchris** [comment] 2024-11-04 17:04
Hi, based on your user ids i can do further research.
Note its not solved i just closed this in favor of keeping all in 1 topic

**Comment by sec252** [comment] 2024-11-04 19:47
@rebelchris 
id: 0FJc4wr3mHqiBN5l2JePC

**Comment by jreyesch** [comment] 2024-11-04 20:46
@rebelchris 
a0p7fsNXz

**Comment by rebelchris** [comment] 2024-11-05 08:29
@jreyesch could you confirm you are in US/LA timezone?
As for @sec252 you are in US/NY timezone?

@sshanzel for your evaluation, maybe the sync on FE doesn't take timezone into account?

**Comment by sec252** [comment] 2024-11-05 13:48
Yes US/NY
