### ISSUE TITLE
🐛 BUG: No posts show up on daily.dev

### ISSUE THREAD

**Issue by AnishDe12020** [dailydotdev/daily#426] opened 2022-01-17 05:29 UTC
### What went wrong? 🤔

Woke up to a blank daily.dev - 
![image](https://user-images.githubusercontent.com/63192115/149712322-f7822640-1115-4b81-9112-36a3c51d69ea.png)
Nothing shows up. Note that I logged out and then suddenly everything showed up but when I logged back in, I again see no posts. Note that this only happens in the popular feed. I can see posts in Best discussions and most upvoted. I have tried different browsers as well.

### Expected Behavior

I should be able to see articles in the popular feed.

### Actual Behavior

No articles show up in the popular feed

### Steps to Reproduce Issue

Make sure you are logged in, check the popular feed if anything shows up. 

### Solution

Don't know.

### Environment

Browser extension Edge 99, PWA Edge 99, website (app.daily.dev) Edge 99, website (app.daily.dev) Chrome 97

#### Operating System

Pop OS 21.10 (Linux)

#### Version of Daily

Extension version v3.12.0, others were the plain website

#### Browser

Browser extension Edge 99, PWA Edge 99, website (app.daily.dev) Edge 99, website (app.daily.dev) Chrome 97

**Comment by avneesh0612** [comment] 2022-01-17 05:46
same for me :(

**Comment by idoshamun** [comment] 2022-01-17 06:25
Can you please share your daily.dev usernames so I can have look?

**Comment by avneesh0612** [comment] 2022-01-17 06:57
https://app.daily.dev/avneesh0612 @idoshamun

**Comment by idoshamun** [comment] 2022-01-17 07:16
@avneesh0612 can you try again, please?

**Comment by avneesh0612** [comment] 2022-01-17 07:32
It only shows me 1 post

**Comment by idoshamun** [comment] 2022-01-17 07:41
I'm pushing a new API version that will help me debug this. Pretty weird issue because I don't see any issue when I'm doing manually the request. But I do see it in production.

**Comment by AnishDe12020** [comment] 2022-01-17 08:01
I also seem to see 1 article appearing at times

![image](https://user-images.githubusercontent.com/63192115/149730427-7133a99b-7c1f-45aa-aa4a-4c09bbfdc393.png)

**Comment by AnishDe12020** [comment] 2022-01-17 08:35
> Can you please check in your network panel a request to `/graphql` that includes a payload with `feed` or `anonymousFeed`?

It is for Feed - 
![image](https://user-images.githubusercontent.com/63192115/149734885-294a83c2-ebc8-45f7-9145-24a388f2c814.png)

And this is the query, prettified - 
```graphql
query Feed(
  $loggedIn: Boolean! = false
  $first: Int
  $after: String
  $ranking: Ranking
  $unreadOnly: Boolean
  $version: Int
) {
  page: feed(
    first: $first
    after: $after
    ranking: $ranking
    unreadOnly: $unreadOnly
    version: $version
  ) {
    ...FeedPostConnection
  }
}

fragment FeedPostConnection on PostConnection {
  pageInfo {
    hasNextPage
    endCursor
  }
  edges {
    node {
      ...FeedPost
      ...UserPost @include(if: $loggedIn)
    }
  }
}

fragment FeedPost on Post {
  id
  title
  createdAt
  image
  readTime
  source {
    id
    name
    image
  }
  permalink
  numComments
  numUpvotes
  commentsPermalink
  author {
    name
    image
    username
  }
  featuredComments {
    id
    content
    permalink
    author {
      name
      image
      username
    }
  }
  trending
  tags
}

fragment UserPost on Post {
  read
  upvoted
  commented
  bookmarked
}
```

**Comment by idoshamun** [comment] 2022-01-17 08:37
Sweet! Thanks a lot :)

**Comment by idoshamun** [comment] 2022-01-17 08:49
I see what's the problem now. We had some issues in our last version in the way we track impressions of articles which caused our algorithm to hide many articles that it thinks are not relevant for you.
I will have to see how I can revert some of it and hopefully, we can release a new version pretty soon with the fix.
Another way to temporarily fix the issue is to add more tags you follow so the algorithm can pick new content for you.

**Comment by avneesh0612** [comment] 2022-01-17 09:00
I see an error now 👀 
![image](https://user-images.githubusercontent.com/76690419/149739128-86567376-10c6-4c34-bc70-a1e4587d8ff6.png)

**Comment by rebelchris** [comment] 2022-01-17 09:24
Hey @avneesh0612 thanks for reporting this error.
I'll look into this right away, I might reach out to you if that's ok with you?

**Comment by idoshamun** [comment] 2022-01-17 09:33
@avneesh0612 @AnishDe12020 I applied a temporary fix that should solve the empty feed issue until we release the new version.
@avneesh0612 please proceed with @rebelchris on fixing the other error you mentioned.
I'll be closing this ticket, for now, please let me know if the issue returns

**Closed by idoshamun** 2022-01-17 09:33 UTC
Labels: Type: Bug

**Comment by AnishDe12020** [comment] 2022-01-17 09:34
> @avneesh0612 @AnishDe12020 I applied a temporary fix that should solve the empty feed issue until we release the new version.
> @avneesh0612 please proceed with @rebelchris on fixing the other error you mentioned.
> I'll be closing this ticket, for now, please let me know if the issue returns

Cool, the articles show up now.

**Comment by avneesh0612** [comment] 2022-01-17 09:35
Clearing the site data worked. @rebelchris probably knows the issue now :)

**Comment by rebelchris** [comment] 2022-01-17 11:45
@avneesh0612 Indeed, thanks for the help appreciate it 👏
Narrowed down the issue you where having with the error showing and we are deploying a fix for that. 🥳

**Comment by avneesh0612** [comment] 2022-01-17 12:55
Awesome!

**Comment by AnishDe12020** [comment] 2022-01-19 07:23
Looks like the issue is back and I have an error log on the console - 

NOTE: only happening on my feed, popular, most upvotes, and best discussions are fine.

![image](https://user-images.githubusercontent.com/63192115/150083123-e2743d7a-4b4a-4b73-a8bc-679d23c29c1e.png)

Got this on another reload - 

![image](https://user-images.githubusercontent.com/63192115/150083257-a532bf17-49f8-455f-9403-f1b01f4ea098.png)

**Comment by rebelchris** [comment] 2022-01-19 07:32
Thanks for logging this @AnishDe12020 We'll look into this again 👀

**Comment by idoshamun** [comment] 2022-01-19 07:38
@AnishDe12020 have you upgraded to 3.13.0?

**Comment by AnishDe12020** [comment] 2022-01-19 08:19
> @AnishDe12020 have you upgraded to 3.13.0?

Not yet, but the problem is gone now (idk why), maybe it was a server which was down?

**Comment by idoshamun** [comment] 2022-01-19 08:31
I applied again the temporary fix. But please make sure to update to the latest version

**Comment by AnishDe12020** [comment] 2022-01-19 08:40
Oh. I have updated it now.
