### ISSUE TITLE
🐛 BUG: My streak doesn't update today

### ISSUE THREAD

**Issue by petehouston** [dailydotdev/daily#1632] opened 2024-12-01 17:57 UTC
### What went wrong? 🤔

My streak stops at 97 today and doesn't update. 

### Expected Behavior

Streak should be updated normally

### Steps to Reproduce Issue

```bash
1. Go to 'daily.dev'
2. Click on 'any post or link'

3. Expect to see streak get updated
```

### Browsers

Chrome

### OS

Mac

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by abhayrsr** [comment] 2024-12-02 12:06
Hey, the issue is similar to #1617 
Team is looking for the solution.

**Comment by rebelchris** [comment] 2024-12-03 06:31
Closing to keep everything in one topic #1617

**Closed by rebelchris** 2024-12-03 06:31 UTC
Labels: Type: Bug
