### ISSUE TITLE
🐛 BUG: GitHub field validation is wrong

### ISSUE THREAD

**Issue by OlaoluwaM** [dailydotdev/daily#251] opened 2021-01-27 23:55 UTC
### What went wrong? 🤔
I was trying to enter my github handle but an error was displayed. I wrote just the handle without the @ symbol and still got the same error. 
Here is a screenshot of what I am talking about

![image](https://user-images.githubusercontent.com/37044906/106069217-b5377100-60c7-11eb-8b90-59ccbc2abb79.png)

### Expected Behavior
It should allow me save my Github handle to my profile

### Actual Behavior
The save changes button is disabled and the Github handle field has a red border-color

### Steps to Reproduce Issue
I am not sure if this is an issue with the way I am inputting it or not, but you can try typing "OlaoluwaM" in a Github handle input for the extension profile settings to see if the error still occurs outside my profile

### Solution
Could you put examples of the correct formats for these fields as their placeholders?

### Environment
Windows 10 Pro
OS Build 19042.746
Chrome version 87

#### Operating System
Windows 10

#### Version of Daily
I think my version is in BETA
![image](https://user-images.githubusercontent.com/37044906/106069751-b1581e80-60c8-11eb-88f6-736ec8798c9b.png)

#### Browser
Chrome version 87
Laptop

**Comment by idoshamun** [comment] 2021-01-28 08:02
Hey!

Thanks for reporting, it's indeed a bug that is caused due to some regex validation we have.
I should change the regex to allow uppercase letters as well.

**Comment by idoshamun** [comment] 2021-01-28 08:46
The issue is now fixed :)

**Closed by idoshamun** 2021-01-28 08:46 UTC
Labels: Priority: Medium, Status: Available, Type: Bug

**Comment by OlaoluwaM** [comment] 2021-01-28 10:04
Thanks
