### ISSUE TITLE
[Bug] profile page layout shift when switching tabs

### ISSUE THREAD

**Issue by ted-dino** [dailydotdev/daily#876] opened 2023-04-21 08:06 UTC
Hi. I noticed an unusual behavior on the page while viewing my profile on the website. the active tab indicator jumps when I scroll down to the "Reputation" tab. i have attached a video to help explain it better. im not a native english speaker so sorry if i made some mistakes in my english :D 

https://user-images.githubusercontent.com/84649871/233579569-848436cd-39fd-4673-aca7-075ccb68d7c3.mp4

**Comment by sshanzel** [comment] 2023-04-24 15:17
@ted-dino thanks for reporting. We've opened this for contributors, let me know if you are keen on fixing this, I'd be glad to help you out 🥳

**Comment by ted-dino** [comment] 2023-04-24 15:50
no problem @sshanzel. Yes, I would love to help out and fix this issue.

**Comment by sshanzel** [comment] 2023-04-25 11:56
> no problem @sshanzel. Yes, I would love to help out and fix this issue.

That's great to hear! I will carve out a plan in the coming days and just fix the environment for you to be able to do the development then I will send you a message 🥳

**Comment by abdulqadeerqureshi** [comment] 2023-04-27 08:38
Hi, I was going through the code. The bug is in the third-party library called `flip-toolkit/lib/types`. Looks like we have to fix it there first.

**Comment by sshanzel** [comment] 2023-05-16 10:51
After careful evaluation, we realized two things. One is we currently don't set the `staleTime` for the queries being used here. Second, one of the causes of the content shift is the unnecessary setting of state on `/[userId]/index` for the `readingHistory` data.

We are planning to fix the points above, though, at the end of the day, we will also apply a loading placeholder to avoid the content shift completely. Let me know if any of you is up for the challenge! 🚀

**Comment by killshot13** [comment] 2023-05-22 03:06
@ted-dino, in light of the new information, are you still planning to have a go at this one?

**Comment by ted-dino** [comment] 2023-05-22 04:36
hey! absolutely! sorry for the late response, but i am definitely up for it.

**Comment by ted-dino** [comment] 2023-05-24 13:23
thanks, will do @sshanzel

**Comment by ted-dino** [comment] 2023-08-10 01:56
Hi @sshanzel . I apologize for the delayed response. I appreciate your understanding. Due to a new job commitment, I find myself rather occupied at the moment. If possible, could you kindly reassign the task from me? Thank you for your consideration.

**Comment by sshanzel** [comment] 2023-08-10 02:04
Hey @ted-dino, all cool. No worries at all. We understand everyone has their own set of priorities, and we were just checking up on the status updates. I didn't unassign the issue so it is still under you. We really thank you for the extra effort you put into this despite having a busy schedule.

**Comment by sshanzel** [comment] 2023-08-10 05:40
Sorry, I think I misunderstood. Let me un-assign the issue now.

**Comment by sshanzel** [comment] 2023-10-27 10:13
Hey there @killshot13, if you are still interested in contributing to this issue, feel free to let me know, so I can assign this to you 🚀

**Comment by killshot13** [comment] 2023-10-29 02:30
Hey sure thing yeah I'll take a stab at it. Thanks @sshanzel

**Closed** 2024-04-10 11:36 UTC
Labels: help wanted, Status: Accepted, Priority: Low, Status: Available, Type: Bug
