### ISSUE TITLE
🐛 BUG: Twitter title is not being shown

### ISSUE THREAD

**Issue by esau-morais** [dailydotdev/daily#202] opened 2020-10-19 15:20 UTC
### What went wrong? 🤔

If I hover the Twitter icon, it's not showing the tooltip with the website title (what is working to the other)

### Expected Behavior

Show website title on hover (all icons)

![Hover LinkedIn icon](https://res.cloudinary.com/emmorais/image/upload/v1603120138/Daily.dev/linkedin_icon_working.png)
_If you see, when I hover the LinkedIn icon, it's showing the website title_

### Actual Behavior

It's not showing website title on hover (specifically, the Twitter icon)

![Hover Twitter icon](https://res.cloudinary.com/emmorais/image/upload/v1603119876/Daily.dev/twitter_icon_not_working.png)
_If you see, when I hover the Twitter icon, it's not showing the website title_

### Steps to Reproduce Issue

1. Open the Daily.dev extension
2. Enable `Recently visited sites` at Daily.dev settings
3. Visit Twitter website `x` times to make sure it's showing at the `Recently visited sites`
4. Hover the icon and see if the tooltip (with the website title) is being shown

### Solution

Verify if Twitter icon (and other websites) is receiving the _className_ `has-tooltip` and other properties.

#### Operating System

ZorinOS (linux)

#### Version of Daily

2.21.1

#### Browser

Firefox (laptop)

**Comment by idoshamun** [comment] 2020-10-20 06:49
Hey!

Thanks for the report. I'll check it out :)

**Comment by idoshamun** [comment] 2020-10-25 13:33
I checked the issue and was not able to reproduce it 🤷‍♂️
I see the "Twitter" tooltip when I hover the Twitter icon.
I'm closing the issue for the time being...

**Closed by idoshamun** 2020-10-25 13:33 UTC
Labels: Priority: Low, Status: Review Needed, Type: Bug
