### ISSUE TITLE
🐛 BUG: Thumbnail showing random image in my post after post creation

### ISSUE THREAD

**Issue by vijaydeepak-tt** [dailydotdev/daily#1295] opened 2024-07-21 15:01 UTC
### What went wrong? 🤔

Similar issue as https://github.com/dailydotdev/daily/issues/1267
![Screenshot 2024-07-21 at 8 26 03 PM](https://github.com/user-attachments/assets/a723bf22-5edd-4110-ad16-75943ba44ba4)

### Steps to Reproduce Issue

```bash
1. Go to ['...'](https://app.daily.dev/squads/tarzzotech)
2. Check the Red squared posts in Attachment.
3. Compare that posts thumbnail in app.dev squad
4. Then click the view post and check the actual blog, and compare both the thumbnails.
5. Both are different.
6. you will be seeing the same for some other blogs as well
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-07-22 06:08
Hi @vijaydeepak-tt,

We have an algorithm that picks the best image for a cover image but maybe it has an issue.
Can you please share direct links to the relevant articles?

**Comment by vijaydeepak-tt** [comment] 2024-07-23 03:03
**Mastering React’s useEffect:**
https://blog.stackademic.com/mastering-reacts-useeffect-common-pitfalls-and-best-practices-885e791a1645

**Building a Simple Chat Application with Socket.io:**
https://blog.stackademic.com/building-a-simple-chat-application-with-socket-io-a-step-by-step-guide-ef1578647880

**Understanding Angular Signals:**
https://blog.stackademic.com/understanding-angular-signals-a-beginners-guide-88c02ccda57a

All these three blogs have wrong thumbnails.

**Comment by idoshamun** [comment] 2024-07-29 08:16
We fixed the thumbnails for the mentioned articles but couldn't find the root cause.
We will continue monitoring it, but I'm closing this issue for now

**Closed by idoshamun** 2024-07-29 08:16 UTC
Labels: Type: Bug
