### ISSUE TITLE
🐛 BUG: Comment dialog box doesn't autofocus when it's opened

### ISSUE THREAD

**Issue by Kvaibhav01** [dailydotdev/daily#246] opened 2021-01-21 13:29 UTC
### What went wrong? 🤔

When someone wants to add a comment after opening a post link inside the Daily app, the **comment box should focus automatically** without the user clicking again in order to start typing their comment.

### Expected Behavior

I expect that when I visit the comment section of a post (for example [this one](https://app.daily.dev/posts/Astu8TDsR)) and click on the "Write a comment" field, then the dialog box which pops up should be in a focused state by default without me to click again on the input area.

Like the following image:

<img width="503" alt="Screenshot 2021-01-21 at 6 48 02 PM" src="https://user-images.githubusercontent.com/11731837/105356309-3d75cc00-5c19-11eb-87dd-5e5d5a6b7cb9.png">

### Actual Behavior

Currently, the input field is not focussed and requires 2 clicks to write a comment.

<img width="515" alt="Screenshot 2021-01-21 at 6 29 15 PM" src="https://user-images.githubusercontent.com/11731837/105356395-58484080-5c19-11eb-8f8b-66389a316ea7.png">

### Steps to Reproduce Issue

Step 1: Click on any post on the feed page.

Step 2: Go down to the article page and click on the "Write your comment" input.

Step 3: The comment dialog box should now pop up. Write a comment by again clicking on the "Write your comment" input.

### Solution

I suppose we can use `autofocus` if we are using an `input` field inside a `form` element. Else, if it's a `div` block then in CSS the `:focus` pseudo-class should be triggered on load.

#### Browser: Firefox Developer Edition version 85.0b9 (64-bit)

**Comment by idoshamun** [comment] 2021-01-21 13:37
Hey @Kvaibhav01,

Great to see you active here as well! 🥳
As you are already familiar with the solution, I think it will be a great chance to contribute to our repository.
If you are up to the challenge, let me know and I'll provide more details 🙏

**Comment by Kvaibhav01** [comment] 2021-01-21 13:40
Hey, @idoshamun for sure! Let me know how to start and more details. I will look into this later. 😄

**Comment by idoshamun** [comment] 2021-01-21 13:53
I see that I already tried to achieve this behavior but I guess something's wrong there.
Here's the exact line where I try to set focus to the element:
https://github.com/dailydotdev/daily-webapp/blob/master/components/modals/NewCommentModal.tsx#L225
We use `div` to make sure it auto grows with the content of the comment.

**Comment by Kvaibhav01** [comment] 2021-01-22 07:14
I see that you invoke the `focus()` method on the `HTMLDivElement` but I'm not too sure how this works as I'm unknown to TS syntax. 😢 (Although it's on my radar to learn next).

As you have already applied the feature, does it work on your machine/browser?

**Comment by esau-morais** [comment] 2021-01-22 12:55
I don't know why, but when I tried to reproduce this (using the component referenced by @idoshamun) it worked perfectly.

**Comment by idoshamun** [comment] 2021-01-24 06:37
@Kvaibhav01 when I wrote it, it used to work but ever since then, the code has changed a few times. These changes might break this functionality. I'll dig into it.

@esau-morais, could you please explain how you tested it? If you don't experience this issue I would love to know :)

**Comment by idoshamun** [comment] 2021-01-24 15:38
The issue is now fixed! :)

**Closed** 2021-01-24 15:38 UTC
Labels: Type: Bug

**Comment by esau-morais** [comment] 2021-01-24 23:49
Sorry for the delay, @idoshamun. As you got to see, error was on the reference. I actually did the same and used the `useRef`. But good to know that it's everything working perfectly neo
