### ISSUE TITLE
🐛 BUG: Pressing Esc key refreshes the posts

### ISSUE THREAD

**Issue by teja463** [dailydotdev/daily#164] opened 2020-06-18 06:27 UTC
### Expected Behavior
I am not sure if this is a feature or a bug

### Actual Behavior
I am not sure if this is a feature or a bug

### Steps to Reproduce Issue
* Install dailynow chrome extension
* Open a new Tab
* Press Escape key. It refreshes the posts
#### Operating System
Windows
#### Version of Daily
2.15.5
#### Browser
Google Chrome Version 83.0.4103.106

**Comment by idoshamun** [comment] 2020-06-18 14:42
Hi! 👋 

Basically, Esc takes you back to the home page not just refreshes your feed.
So for example, if you are looking on a single tag/source feed or searched for something hitting Esc will clear everything.
I believe that's not a bug, so I'm closing this issue.
If you think otherwise feel free to reopen and discuss.

**Closed by idoshamun** 2020-06-18 14:42 UTC
Labels: Type: Bug
