### ISSUE TITLE
🐛 BUG: I can't remove mastodon.social link from my profile

### ISSUE THREAD

**Issue by entroxxtpm** [dailydotdev/daily#1448] opened 2024-09-20 16:52 UTC
### What went wrong? 🤔

I can't remove my Mastodon link from my profile.

### Expected Behavior

I should be able to remove the link.

### Steps to Reproduce Issue

```bash
1. Go to 'your profile'
2. Click on 'Edit profile'
3. Scroll down to 'Mastodon Link'
4. Try to remove it (if you have it)
```

### Solution Proposed

I should be able to remove the link.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11 Pro, Chrome 128.0.6613.138

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

Latest version.

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-09-20 16:54
Hi @entroxxtpm,

Thanks for raising it.
I'm closing this one as it's duplicate of: https://github.com/dailydotdev/daily/issues/1396

Let's keep the discussion there.

**Closed by rebelchris** 2024-09-20 16:54 UTC
Labels: Type: Bug
