### ISSUE TITLE
🐛 BUG: Duplicate news items shown in my feed

### ISSUE THREAD

**Issue by allentv** [dailydotdev/daily#1491] opened 2024-10-11 10:01 UTC
### What went wrong? 🤔

After every page or two of scrolling in Chrome, I see previous news cards in the feed.

### Expected Behavior

I expect not to see duplicate news cards

### Steps to Reproduce Issue

```bash
1. Open new tab
2. Scroll through the news feed
```

### Screenshots

```bash
![bug-report](https://github.com/user-attachments/assets/89669f61-8c5c-4544-8bbe-b43c86c7ddca)
```

I have highlighted the duplicate news cards in yellow

### Environment

Windows 11 (Home), Chrome Version 129.0.6668.90 (Official Build) (64-bit)

### Browsers

Chrome

### OS

Windows

### Version of daily.dev

3.34.6

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-10-11 11:52
@allentv Thanks for reporting we'll investigate.
In the meantime I think it might be a duplicate of: https://github.com/dailydotdev/daily/issues/1479

Closing in favor of keeping the duplication issue in one thread.

**Closed by rebelchris** 2024-10-11 11:52 UTC
Labels: Type: Bug
