### ISSUE TITLE
🐛 BUG: cannot remove "website" URL from profile once it has been entered & saved

### ISSUE THREAD

**Issue by yairEO** [dailydotdev/daily#1422] opened 2024-09-10 18:50 UTC
### What went wrong? 🤔

cannot remove "website" URL from profile once it has been entered & saved

https://jam.dev/c/9b50cbe9-8cdf-41f6-a4ff-5d43a2158149

### Steps to Reproduce Issue

```bash
1. Go to "edit profile" page
2. remove "website" URL
3. Save
4. Refresh
5. Still shows "website" URL field is filled with previous data
```

### Screenshots

```bash
https://jam.dev/c/9b50cbe9-8cdf-41f6-a4ff-5d43a2158149
```

### Browsers

Chrome

### OS

Windows

### Additional Context

```bash
all in the JAM link
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-09-11 06:07
Duplicate of https://github.com/dailydotdev/daily/issues/1396

Closing this one to keep the conversation there.

**Closed by rebelchris** 2024-09-11 06:07 UTC
Labels: Type: Bug
