### ISSUE TITLE
[Bug 🪲]: Can't close the option menu by clicking the menu button

### ISSUE THREAD

**Issue by ashrafchowdury** [dailydotdev/daily#940] opened 2023-07-17 06:30 UTC
## Description

When the option **menu is open, clicking the menu button does not close the menu**. This leaves the menu open and damages the user experience.

## Bug Preview

https://github.com/dailydotdev/apps/assets/87828904/15904c1e-a244-4c5b-859e-4a681a272f73

**Comment by idoshamun** [comment] 2023-07-23 06:14
@ashrafchowdury thanks for reporting!

**Comment by ashrafchowdury** [comment] 2023-07-23 12:21
> @ashrafchowdury thanks for reporting!

----

**I would like to work on this issue**

**Comment by sshanzel** [comment] 2023-07-24 04:50
Hi @ashrafchowdury, thanks for your interest in working with the said issue. To start off, you can find this implementation on `PostModalActions`, but the core concern here is the handler when clicking the button. The function should work as a toggle that if the menu is already open, we should just close it as you reported.

**Comment by sshanzel** [comment] 2023-08-09 05:49
Hi @ashrafchowdury, let me know if you are still interested in this issue. If not, it is totally cool but we will have to un-assign to free it up to those who are looking to participate.

**Comment by ashrafchowdury** [comment] 2023-08-10 04:58
Can I use a `useState` to control the toggle function?

**Comment by sshanzel** [comment] 2023-08-10 05:39
> Can I use a `useState` to control the toggle function?

Yes, the popup needs to be in a controlled state. There should be a hook named `useContextMenu` that is widely used where we can store the state.

**Comment by ashrafchowdury** [comment] 2023-08-10 07:38
Added a `useState` to control the flow of the `onMenuClick` function and it's working properly.

![image](https://github.com/dailydotdev/daily/assets/87828904/caf5e821-5a3d-44a0-90ae-4679b5f1877b)

**Comment by sshanzel** [comment] 2023-08-10 07:40
Nice to hear it works as intended now! Thank you for your effort 🙏 

Feel free to fork the repo and raise a PR so we can discuss more the fix 🥳

**Comment by ashrafchowdury** [comment] 2023-08-10 10:52
**Raised PR**  https://github.com/dailydotdev/apps/pull/2033

**Comment by sshanzel** [comment] 2023-10-27 10:10
We can close this now as you have amazingly contributed to fixing it. Thank you again! :shipit:

**Closed by sshanzel** 2023-10-27 10:10 UTC
Labels: help wanted, Status: Accepted, Priority: Low, Type: Bug
