### ISSUE TITLE
🐛 BUG: Styling on squads 

### ISSUE THREAD

**Issue by gui1612** [dailydotdev/daily#1027] opened 2023-11-25 22:13 UTC
### What went wrong

Even though Squads are still in beta, here are some problems that I found while using them:

- **Problem 1:** The images inside the post container don't have a fixed size such as in the regular feed. This makes the overall look of the squad pages a bit inconsistent.

- **Problem 2:** The `reading history` and `Post` buttons don't have a gap between each other and the `Post` button doesn't have a gap between itself and its parent container.

- **Problem 3:** In the `reading history`, in posts where the picture does not exist and is substituted by the initial part of the title, sometimes it overlaps the element below.

### Expected Behavior

- **Problem 1:** The images should have a coherent styling and should be the same size, independently of the size of the description or the thumbnail's image. 

- **Problem 2:** There should be no `Post` button inside the textbox when it's not on hover (since there is nothing to post) and the `reading history` href should have a gap on its right side, separating it from its parent

- **Problem 3:** The posts should be correctly spaced without contenting being shared between themselves. I would also suggest placing an image in there instead of the title even if it was a filler one, but that is not the scope of the problem and can be somewhat opinionated.

### Steps to Reproduce Issue

```
Problems 1 and 2:

1. Go to squads
2. Join a squad
3. Go to that squad's page
4. See the error

Problems 3:

1. Go to squads
2. Join a squad
3. Go to that squad's page
4. Click on reading history
4. See the error
```

### Solution Proposed

- **Problem 1**: The size of the image relatively to the container itself is fixed, to ensure a consistent size as in the regular feed.

- **Problem 2:** Remove the post button whenever the textbox is not on hover since it is not needed until it has some text on it.

- **Problem 3:** Limit the amount of text displayed in the title, or take it into consideration in the styles to resize the container accordingly.

#### Problem 1
![Problem 1 - 2023-11-25 14-30-07](https://github.com/dailydotdev/daily/assets/16765627/7218bf85-6dcc-4fd6-b4bd-1717e7571596)

#### Problem 2
![Problem 2 - 2023-11-25 19-41-21](https://github.com/dailydotdev/daily/assets/16765627/c2f1ba06-217f-47d9-bdcb-6e9f0a4a7882)

#### Problem 3
![Problem 3 - 2023-11-25 22-05-19](https://github.com/dailydotdev/daily/assets/16765627/d03d6061-31fb-4937-9f62-23d008cbc2d8)

### Environment

6.5.9-1-MANJARO, Firefox Developer Edition 120.0b3 (tested on chrome too)

### Browsers

Firefox

### OS

Linux

### Version of daily.dev

3.28.4

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2023-11-26 07:40
Hi @gui1612,

Thank you for the detailed bug report.
I see that the image for problem 1 is broken. Could you please fix it? I'm not sure I understand.

**Comment by gui1612** [comment] 2023-11-26 15:46
I'm glad to help @idoshamun!
The broken image should be fixed by now.

**Comment by idoshamun** [comment] 2023-11-27 06:32
@gui1612 thanks for fixing. As for problem 1, it's a feature not a bug :P
Our design team wanted to make this space adjustable to the commentary written by the user

**Comment by gui1612** [comment] 2023-11-27 11:40
Personally, I think it would be a good improvement to either have its size fixed when it goes to the "regular feed" section or to have an easy approachable option to remove the squad posts from the main feed (maybe in `Feed Settings` or something similar)

Regarding the feature, I can see reasons to do it on the squad page, because all posts have that styling, but when they get displayed in the user's feed, it does look a bit more glitchy since the other containers all have fixed sizes.

Having this said, take my opinion with a huge grain of salt. I'm trying to provide as much user feedback as possible, but this is a matter of personal opinion. 😅

**Comment by sshanzel** [comment] 2023-11-27 21:34
To set things clear, we currently consider items 2 and 3 as valid issues. The fix for item 2 should be obvious (remove the unnecessary spacing in between). For Item 3, the text came from the image being unable to render, hence, the `alt` text of the image was rendered, we should maybe put a more concise message than repeating the post's title.

**Comment by gui1612** [comment] 2023-11-29 11:34
Looks like a good option to me @sshanzel! 
Tell me if I can help in any way, either in the development process or by providing feedback. :)

**Comment by gui1612** [comment] 2023-12-03 21:18
Okay, I'll look at it during the week! :)

**Comment by sshanzel** [comment] 2024-07-15 12:10
The issues mentioned here should have been fixed by the internal team. If the issue persists, feel free to reopen this ticket. We understand that you wanted to help here, but some of our internal initiatives have come across the issues reported and we had to fix them. Thank you for your interest and hope to see you raise some PRs soon.

**Closed by sshanzel** 2024-07-15 12:10 UTC
Labels: help wanted, Status: Accepted, Status: Available, Type: Bug
