### ISSUE TITLE
🐛 BUG: Streak Delayed/Untracked

### ISSUE THREAD

**Issue by MCBrueggman** [dailydotdev/daily#1614] opened 2024-11-22 13:27 UTC
### What went wrong? 🤔

Over the last 2 days, I tried to keep my streak up, however, it didn't track on Thursday the 21st, and said that I didn't read any articles that day, despite the fact that i made a post that day. and for today, I read an article and it tracked the article for yesterday

### Expected Behavior

I should have a streak of 69 days, not 68 days, and it should show that I read plenty of articles on Thursday and Friday

### Steps to Reproduce Issue

```bash
1. Go to landing page
2. Click on any article
3. Follow the link to said article
4. Read the article
5. Return to page to see streak increase
```

### Solution Proposed

Just make sure that people's streaks don't fall on events like this

### Screenshots

![image](https://github.com/user-attachments/assets/a483dd92-5530-4132-abc2-8ed7d854eaba) ![image](https://github.com/user-attachments/assets/decbcc2e-e7ac-4202-accb-5ba989a619b4) ![image](https://github.com/user-attachments/assets/8ad8edb3-2893-47bd-bb7e-ce24c037be61)

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment] 2024-11-22 14:16
Hi @MCBrueggman. Thank you for reporting. Can you check if you have your timezone correctly set through this page? https://app.daily.dev/account/notifications

**Comment by MCBrueggman** [comment] 2024-11-22 14:20
To Lee,
My timezone is set to UTC-5 (Eastern USA). I'm not sure what it could be, but I do know that it's unlikely to be on my end
-Mike Brueggman

________________________________

**Comment by sshanzel** [comment] 2024-11-22 14:33
Does the issue still persist after refresh? I checked in our DB and you seem to have your streak for today as recorded. However, the value 68 seems to be the right value for your account, and the issue is a UI glitch if it still does.

**Comment by MCBrueggman** [comment] 2024-11-22 15:14
It's just a UI issue, not a database issue. The streak just needs to show as good for today.

________________________________

**Comment by sshanzel** [comment] 2024-11-22 16:30
Yep. [Raised a PR](https://github.com/dailydotdev/apps/pull/3873) for it now. Once merged, it should fix the issue 👀

**Comment by vishxly** [comment] 2024-11-23 08:47
Dear Daily.dev Support Team,

I hope this message finds you well. I am writing to follow up on my previous message regarding the visibility issues with my Daily.dev account (username: vshall).

It has been over week since I reached out via email, but I have not received a response. Since I haven't heard back, I am writing this message here on GitHub in the hopes of resolving the issue.

To recap, my profile and posts are not visible on the platform, preventing effective interaction and sharing within the community. If there are specific reasons for this or any actions I need to take, please let me know.

I understand your team may have a busy schedule, but I would greatly appreciate any update or guidance on how to address this matter at your earliest convenience.

Thank you for your time and support. I look forward to your response.

Best regards,
Vishal Yadav

**Comment by rebelchris** [comment] 2024-12-03 06:40
Closing in favor of #1619

**Closed by rebelchris** 2024-12-03 06:40 UTC
Labels: Type: Bug
