### ISSUE TITLE
🐛 BUG: Daily.go mobile App

### ISSUE THREAD

**Issue by Wusabinga** [dailydotdev/daily#192] opened 2020-09-29 08:48 UTC
### What went wrong? 🤔

On Startup your PWA I got an login scren, but login with Github fails. I can log me in, but got redirected to your loginpage again.
First I got a URL go.dailynow.co/login?from.... and after login with github I got only go.dailynow.co/login.

### Expected Behavior

    I expect to get logged in.

### Actual Behavior

    I got redirected to your login screen

### Steps to Reproduce Issue

  1. Got to your login page. go.dailynow.co/login?from=%2Ftoilet
  2. Click on Login with Github.
  3. Login with Github
  4. Get redirected to go.dailynow.co/login

#### Operating System

Android 10

#### Version of Daily

PWA/Webpage

#### Browser

    Browser info:
        Chrome 85.0.4183.127
    Mobile device!?
       Nokia 7.1

**Comment by idoshamun** [comment] 2020-09-29 19:27
Hey!
Could you elaborate what is the bug exactly?

**Comment by Wusabinga** [comment] 2020-09-29 22:22
Oh damned.. Sorry :( Filled out but it's empty... I Edit this bug report right now.

**Comment by idoshamun** [comment] 2020-09-30 12:11
Actually, this app is not maintained anymore and we're about to take it down.
With that said, I'll try to fix it when I have some free time.

**Comment by Wusabinga** [comment] 2020-09-30 15:12
Oh that´s sad to hear :( Is it a dicision because of to less time or to less using from costumers? I mean, hmm i saw it´s javascript, a lot of vue.js code. I don´t know about vue, but i can learn it. Btw i wanted to learn it later, but i can get it forward so i learn it earlier and maybe i could help you a bit or try it

**Comment by idoshamun** [comment] 2020-10-01 06:02
Don't worry! We're slowly making a new one.
The main issue is that we're a small team and cannot maintain everything.
We're focusing on delivering as much value as we can, given our workforce.

**Comment by Wusabinga** [comment] 2020-10-01 11:28
Good to hear. Unfortunately, I'm still at the very beginning of my career. Although I should know HTML, CSS and JS, I almost don't dare to ask where I can help you.

**Comment by idoshamun** [comment] 2020-10-05 13:39
Don't worry. Thank you for being so kind!

**Comment by idoshamun** [comment] 2020-10-06 08:30
The issue is now fixed.
You should be able to log-in and the app works properly
https://go.daily.dev

**Closed by idoshamun** 2020-10-06 08:30 UTC
Labels: Type: Bug
