### ISSUE TITLE
🐛 BUG:  The streak does not update properly if the new tab page remains open after midnight 

### ISSUE THREAD

**Issue by catalincodes** [dailydotdev/daily#1225] opened 2024-06-18 13:18 UTC
### What went wrong? 🤔

The streak did not update correctly. I'll explain in the Steps to Repro. See screenshot below.

### Expected Behavior

The streak should display all days checked.

### Steps to Reproduce Issue

```bash
1. Have the new tab (daily.dev) opened overnight (i.e. in my case from Sunday night over to Monday morning)
2. Next day (i.e. on Monday for me), open an article and click "Read Post".
3. Streak value gets be incremented. The Monday reminds unchecked showing the red-dotted line.
4. The next day on Tuesday you still have the streak alive, because you did read a post on Monday, but the graph does not get updated.
```

### Screenshots

![image](https://github.com/dailydotdev/daily/assets/12548925/56eab970-66bb-44b3-89f0-8f3d41f331d5)

### Environment

visible accross multiple browsers and OS

### Browsers

Chrome

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by catalincodes** [comment] 2024-06-18 13:21
Addendum:
Now after reading the Tuesday article:

![image](https://github.com/dailydotdev/daily/assets/12548925/3fc0b204-6939-4c52-a138-66e57c494b5f)

**Comment by idoshamun** [comment] 2024-06-23 07:34
Hi @catalincodes,

I think it's because our authentication expires after a while. My suggestion is to refresh the tab if you keep it open for a while.
Please let me know if it works

**Comment by rebelchris** [comment] 2024-07-14 13:40
Closing as intended for now.

**Closed by rebelchris** 2024-07-14 13:40 UTC
Labels: Type: Bug

**Comment by catalincodes** [comment] 2024-07-14 18:09
Hi!

Just wanted to say, that yes, you need to refresh the tab, especially if it was opened the previous day (or before midnight). I understand the limitation and I know that really there is nothing that can be done about it. 

So yeah, it works, of course. I expected the streak would communicate in a WebSockets kind of way (where it updates instantly). For example if it's 11:59pm and it shows that your streak is 2 days, then at 12:00am, midnight, it would show the incomplete streak button with a circle of dashes. That's not the case and a tab refresh is required. 

There is also the possibility that this does work, but only on daily.dev itself and on the new tab page. Regardless... as @rebelchris said and I quote, this is `as intended`.
