### ISSUE TITLE
🐛 BUG: popup should close on outside click

### ISSUE THREAD

**Issue by GouravKumar13** [dailydotdev/daily#1094] opened 2024-03-12 22:58 UTC
### What went wrong? 🤔

![image](https://github.com/dailydotdev/daily/assets/55110247/e40c128c-d39a-4855-b272-b1ca91af38db)
![image](https://github.com/dailydotdev/daily/assets/55110247/5698fe4b-1a25-4b9b-be96-bc8468409d0e)

 

### Expected Behavior

This section should close as soon as the user click out of the container or press esc 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Solution Proposed

we can add event listener to the component  to achieve the desired output

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Brave

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment] 2024-03-16 02:53
Hey! Thank you for reporting. We agree that it should close you click outside of its elements. If you are interested in contributing, feel free to check the `CompanionPopupButton`. There is an instance of `SimpleTooltip` and that component itself accepts a prop that when you click outside, the callback will be triggered which we can use to set the visibility of the popup to false. Let me know if you need any help bootstrapping up!

**Comment by shachargiladi** [comment] 2024-03-28 13:39
Is someone working on it? I will be happy to take this issue

**Comment by sshanzel** [comment] 2024-04-01 08:57
Hi @shachargiladi, feel free to take it on, you can try and emulate the components in our webapp [through GitPod](https://gitpod.io/#https://github.com/dailydotdev/apps/) since the development of the extension locally is still being worked on. With that, kindly check the message above on how we should go about it.

**Comment by shachargiladi** [comment] 2024-04-01 17:42
@GouravKumar13 can you give more details on how to reproduce the bug? it seems fixed to me when I'm trying to reproduce it

**Comment by GouravKumar13** [comment] 2024-04-02 02:04
@shachargiladi  when you will add daily dev as an extension and open a new tab you will see the issue 
![image](https://github.com/dailydotdev/daily/assets/55110247/fcec1c0a-7f73-4c64-bf37-facaf9adec28)

**Comment by sshanzel** [comment] 2024-04-04 10:25
> @sshanzel hey,
I'm getting the following error while trying to run the db migrations locally (using gitpod as you suggested):

Hey. So sorry for the issue with the setup. I will get back to you on this.

**Comment by sshanzel** [comment] 2024-04-15 13:09
@shachargiladi apologies for the time taken, we just merged a fix of our GitPod environment. Feel free to re-start the setup. Let us know if you encounter anything weird! 🙌

**Comment by shachargiladi** [comment] 2024-04-19 11:46
Hey, thanks for the help!
the problem solved
however, now i am getting "not found" error on one of the packages in the package.json: "ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@dailydotdev%2Feslint-plugin-daily-dev-eslint-rules: Not Found - 404"

Any chance you know where can I find thre package **"@dailydotdev/eslint-plugin-daily-dev-eslint-rules"**? when I was looking in the npm registry I found only 4 packages of @dailydotdev.

Thanks

**Comment by rebelchris** [comment] 2024-04-19 13:05
@shachargiladi this happens on pnpm9

You can either repull main where we fixed this, or manually set pnpm to latest 8 version 🙏

**Comment by shachargiladi** [comment] 2024-04-21 19:38
@sshanzel 
Hey, I am not sure how to link my pr to thw issue so I added the relevant url. This is my first time contributing so I would love to hear any comments you have so I can fix and improve for next time :)

[https://github.com/dailydotdev/apps/pull/3029](url)

**Comment by sshanzel** [comment] 2024-04-24 11:43
@shachargiladi thank you for [fixing the issue](https://github.com/dailydotdev/apps/pull/3029), this should not happen anymore after our next publication of our extensions 🥳 🎉

**Closed by sshanzel** 2024-04-24 11:43 UTC
Labels: help wanted, Status: Accepted, Type: Bug
