### ISSUE TITLE
🐛 BUG: The circle is not marked after I read the articles 

### ISSUE THREAD

**Issue by AndrewAct** [dailydotdev/daily#1629] opened 2024-11-29 17:56 UTC
### What went wrong? 🤔

Hey team,
I found the progress circle is not marked after I read the articles. A screenshot is attached.
I tried to refresh the pages or open a new tab, but this issue persists. This issue has occurred for a few days, and it was not fixed. Can someone please have a look? Thank you.

Best,
Andrew
![Screenshot 2024-11-29 at 11 54 49 AM](https://github.com/user-attachments/assets/3b70a459-2499-4d7c-b71d-5a8c795a8f90)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by gouldcs** [comment] 2024-11-29 20:52
This has also been an issue for me on all platforms and multiple browsers. Chrome, Safari, on desktop and mobile.

Seems to be tracking completion one day behind, but the actual counter updates correctly. Started happening to me maybe a week ago.

**Comment by idoshamun** [comment] 2024-12-01 11:54
Hi @AndrewAct,

We will look into it

**Comment by sshanzel** [comment] 2024-12-02 05:49
@AndrewAct @gouldcs kindly check if your timezone was set on your profile correctly. Should be found here: https://app.daily.dev/account/notifications

Example

![Screenshot 2024-12-02 at 1 49 13 PM](https://github.com/user-attachments/assets/3d63fc80-88c9-47cc-9e31-bddfd5b4f357)

**Comment by rebelchris** [comment] 2024-12-03 06:38
Duplicate of #1619 closing this to keep all comms there.

**Closed by rebelchris** 2024-12-03 06:38 UTC
Labels: Type: Bug
