### ISSUE TITLE
🐛 BUG: Claimed articles not displaying on profile

### ISSUE THREAD

**Issue by mjgardner** [dailydotdev/daily#276] opened 2021-04-26 17:47 UTC
### What went wrong? 🤔

I have written [several articles on dev.to](https://dev.to/mjgardner) and [DZone](https://dzone.com/users/4518905/mjgardner.html) appearing on my daily.dev feed page, but they are not being picked up as being authored by me despite having followed the instructions and adding [my Twitter handle](https://twitter.com/markjgardner) to [my daily.dev profile](https://app.daily.dev/mjg).

### Expected Behavior

Articles should be listed on [my profile page](https://app.daily.dev/mjg) under "Your Articles".

### Actual Behavior

Only two of the articles are displaying.

### Steps to Reproduce Issue

1. Create new tab in browser with daily.dev installed so that the daily.dev feed displays.
2. Search for the `#perl` tag.
3. Note that stories authored by me are showing up.
4. Go to [my daily.dev profile page](https://app.daily.dev/mjg).
5. Note that only two of those stories are displayed.

### Solution

NA

#### Operating System

macOS Catalina 10.15.7

#### Version of Daily

2.30.3

#### Browser

Chrome 90.0.4430.85

**Comment by idoshamun** [comment] 2021-04-27 06:41
Hey @mjgardner!

The issue is now fixed :)
Sorry for that

**Comment by mjgardner** [comment] 2021-04-27 14:16
Really? I don't see the articles on [my profile page](https://app.daily.dev/mjg).

<img width="647" alt="Screen Shot 2021-04-27 at 9 14 43 AM" src="https://user-images.githubusercontent.com/133483/116256784-1effff00-a739-11eb-98e5-8bfa9b3c3b29.png">

**Comment by idoshamun** [comment] 2021-04-27 14:22
Oh, I thought you meant these two.
Could you please refer me to the other articles on daily.dev that you wrote?

**Comment by mjgardner** [comment] 2021-04-27 14:28
- [The Perl Debugger Can Be Your Superpower](https://api.daily.dev/r/9k0OLNxEV)
- [Better Perl: Using map and grep](https://api.daily.dev/r/2iGwzlauG)
- [Video for Better Perl: Subroutine Signatures and Type Validation](https://api.daily.dev/r/JTf1iGByp)
- [Perl and XML in 2021: A Few Lessons Learned](https://api.daily.dev/r/PmtP5ULiY)
- [The Attraction of Test::Fatal in Perl](https://api.daily.dev/r/P0ZGaElsi)
- [Avoid CPAN Conflicts in Your Personal Perl Modules](https://api.daily.dev/r/uDZYinhiu)
- [Localizing Dates in A Perl Web Application](https://api.daily.dev/r/Ldanelghk)

**Comment by idoshamun** [comment] 2021-04-29 18:29
Please check again :)

**Comment by mjgardner** [comment] 2021-04-29 18:31
Thanks. This will continue to be updated OK as I publish more?

**Comment by idoshamun** [comment] 2021-04-29 18:39
It should. And if not please let us know.

**Closed by idoshamun** 2021-04-29 18:39 UTC
Labels: Type: Bug
