### ISSUE TITLE
🐛 BUG: Keep getting logged out

### ISSUE THREAD

**Issue by junaidahmed501** [dailydotdev/daily#165] opened 2020-06-23 05:26 UTC
## 🐛 Bug Report
Not sure about the time interval but I get logged out at least once a time during one day & have to login again.

### Steps to Reproduce Issue
I use Github to Daily & this is the only step I know so far.

#### Operating System
Ubuntu 18.04
#### Version of Daily
2.15.7
#### Browser
Firefox 77.0.1

**Comment by idoshamun** [comment] 2020-06-23 06:17
Hi @junaidahmed501,

Thanks for reaching out 🤩
Do you see anything suspicious in the logs?
Did it start with the release of the new version 2.15.7?

**Comment by junaidahmed501** [comment] 2020-06-23 10:13
> Hi @junaidahmed501,
> 
> Thanks for reaching out star_struck
> Do you see anything suspicious in the logs?
> Did it start with the release of the new version 2.15.7?

Actually I don't know about the logs though but I think it could be version 2.15.7 because I have been facing the issue since last week & so It is definitely a recent issue though, I think :]

**Comment by idoshamun** [comment] 2020-06-23 13:17
Unfortunately, I was not able to reproduce this issue.
Could you please reinstall the extension and let me know if this resolves the problem?

**Comment by junaidahmed501** [comment] 2020-06-24 06:39
@idoshamun yeah sure, I'll give it a try.

**Comment by idoshamun** [comment] 2020-07-15 05:06
I'm closing this issue if it happens again feel free to open again.

**Closed by idoshamun** 2020-07-15 05:06 UTC
Labels: Status: Blocked, Type: Bug
