### ISSUE TITLE
🐛 BUG: Recommended feed data is stucked (or missing?)

### ISSUE THREAD

**Issue by ZhenningLang** [dailydotdev/daily#1391] opened 2024-09-02 01:59 UTC
### What went wrong? 🤔

Data of my feed does not appear as expected. 
When I switch the sorted radio from "Recommended" to "By date", everything works well.

So I guess the recommend content feed may encounter some problems.

![1725242250654](https://github.com/user-attachments/assets/9915c0c0-fb1f-4241-8b18-498f749ce99c)

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

3.34.0

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-09-02 04:54
Duplicate of https://github.com/dailydotdev/daily/issues/1392
Keeping all discussion there.

**Closed by rebelchris** 2024-09-02 04:54 UTC
Labels: Type: Bug
