### ISSUE TITLE
🐛 BUG: 

### ISSUE THREAD

**Issue by BearWithIvan** [dailydotdev/daily#1167] opened 2024-05-16 13:34 UTC
### What went wrong? 🤔

On the `Customize` modal, on preferences section, when switch fast `Enable companion` the app crash. The error in console is: `TypeError: a is not a function`

### Expected Behavior

App should not crash

### Steps to Reproduce Issue

```bash
1. Go to 'Main page'
2. Click on 'Customize'
3. Switch fast 'Enable companion'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

### Additional Context

```bash
TypeError: a is not a function
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-05-19 07:11
Hi @BearWithIvan,

Thanks for the report! Just to verify, you use the extension right?

**Comment by BearWithIvan** [comment] 2024-05-27 14:39
Hi @idoshamun, 
I think yes.

**Comment by idoshamun** [comment] 2024-05-29 15:22
Unfortunately, we were not able to reproduce. So any lead on how to reproduce will be appreciated

**Comment by rebelchris** [comment] 2024-07-14 13:35
closing as we can't reproduce/no answer.

**Closed by rebelchris** 2024-07-14 13:35 UTC
Labels: Type: Bug
