### ISSUE TITLE
🐛 BUG: The style of the input field changes when using autocomplete

### ISSUE THREAD

**Issue by hiteshwadhwani** [dailydotdev/daily#1059] opened 2024-01-15 17:04 UTC
### What went wrong? 🤔

The styling of the input field changes when using autocomplete 

### Expected Behavior

It should use the same styling when using autocomplete as well

### Steps to Reproduce Issue

```bash
1. Go to the Sign-in or Login page
2. Fill the Input field using autocomplete
3. The styling of the input field will change
```

### Screenshots

```bash
https://jmp.sh/4tABksY8
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by sshanzel** [comment] 2024-01-16 03:47
Duplicate of https://github.com/dailydotdev/daily/issues/877

**Closed by sshanzel** 2024-01-16 03:47 UTC
Labels: Type: Bug
