### ISSUE TITLE
🐛 BUG: Open Wrong post when click on a card

### ISSUE THREAD

**Issue by this-claudio** [dailydotdev/daily#1161] opened 2024-05-13 15:00 UTC
### What went wrong? 🤔

It was opening the wrong post when some card os clicked

https://github.com/dailydotdev/daily/assets/65410959/ee601238-6f7c-455d-91f8-a28c7b9ef29f

### Expected Behavior

Open the clicked post

### Steps to Reproduce Issue

```bash
1. Go to Home Page
2. Click on a card
3. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-07-14 13:34
Unable to reproduce and no remarks back so closing for now.

**Closed by rebelchris** 2024-07-14 13:34 UTC
Labels: Type: Bug
