### ISSUE TITLE
🐛 BUG:  Search option is not working

### ISSUE THREAD

**Issue by thushar-p** [dailydotdev/daily#1284] opened 2024-07-17 03:35 UTC
### What went wrong? 🤔

I wanted to search for a topic and couldn't see the results.

### Expected Behavior

It should have responded with the result. But it was an empty page

### Steps to Reproduce Issue

```bash
1. Go to ' search tab on android app '
2. Click on ' search bar'
3. Search for any thing and click on any recommended topics. The results are not rendered.
```

### Solution Proposed

I have not debugged or did any kind of research.

### Screenshots

```bash
.
```

### Environment

Android smartphone

### Browsers

Other

### OS

Android

### Version of daily.dev

13

### Additional Context

```bash
.
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-07-17 05:05
Thanks for reporting!
Well look into it urgently

**Comment by rebelchris** [comment] 2024-07-17 06:52
@thushar-p Thanks again for reporting.
We deployed a fix for this issue and it should work as intended now 🙏

**Closed by rebelchris** 2024-07-17 06:52 UTC
Labels: Type: Bug

**Comment by thushar-p** [comment] 2024-07-17 11:15
Great @rebelchris. Thanks for the quick fix 👍
