### ISSUE TITLE
🐛 BUG: Bugged transition when trying to add a custom shortcut

### ISSUE THREAD

**Issue by avi12** [dailydotdev/daily#1386] opened 2024-09-01 06:52 UTC
### What went wrong? 🤔

https://github.com/user-attachments/assets/32b92724-e530-444c-8601-606c213d7a7c

### Steps to Reproduce Issue
1. type a partial URL like `https://s`
2. Delete the last character ("s" in this case)

### Environment

Chrome extension on Edge

### Browsers

Microsoft Edge

### OS

Windows

### Version of daily.dev

3.34.0

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-09-04 05:16
Hi @avi12,

Thanks for reporting, we will look into that :)

**Comment by sshanzel** [comment] 2024-09-06 14:51
Closing as duplicate of https://github.com/dailydotdev/daily/issues/1357

**Closed by sshanzel** 2024-09-06 14:51 UTC
Labels: Type: Bug
