### ISSUE TITLE
🐛 BUG: Reading streak not updating

### ISSUE THREAD

**Issue by mihai-ro** [dailydotdev/daily#1538] opened 2024-10-24 13:33 UTC
### What went wrong? 🤔

The reading streak stopped updating.

### Expected Behavior

When opening and reading an article, daily.dev catches this event and increments the reading streak.

### Steps to Reproduce Issue

```bash
1. Go to daily dev.
2. Click on any article and open it.
3. Check the reading streak.
```

### Screenshots

```bash
![video of the issue](https://streamable.com/84tezz)
```

### Environment

MacOS Sequoia

### Browsers

Chrome

### OS

Mac

### Version of daily.dev

latest

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-10-25 06:35
Hi @mihai-ro ,

Thanks for reporting, we do see the views on your user and that you maintained a streak that day atleast.
We're looking into why it didn't reflect for these views.

Thanks a lot for the recording that massively helped.

**Comment by mihai-ro** [comment] 2024-10-26 00:36
Cheers @rebelchris. btw, I replicated this issue again today. It has something to do with time zones.

**Comment by rebelchris** [comment] 2024-10-28 06:45
Hi @mihai-ro ,

could you check if your timezone is correctly set here?
https://app.daily.dev/account/notifications

**Comment by mihai-ro** [comment] 2024-10-29 11:15
Sadly, that did not fix it. I used that "use reputation to restore" ability.

<img width="693" alt="Screenshot 2024-10-29 at 07 15 05" src="https://github.com/user-attachments/assets/bbfbcf27-f2c6-47b0-85b9-10768564ba1c">

**Comment by idoshamun** [comment] 2024-11-03 13:47
@mihai-ro we'll look into it. Sorry about that 🙏

**Comment by rebelchris** [comment] 2024-11-04 06:10
@mihai-ro We restored your streak and recovered the points you used.
We are further investigating the issue

**Comment by robbpage** [comment] 2024-11-07 13:48
@rebelchris my userID is buckrussell

I checked the Timezone and it's set properly.

**Comment by mihai-ro** [comment] 2024-11-07 14:53
@rebelchris for some reason it went to 0 and I can't even recover it with points. It did say it was recorded yesterday.

**Comment by sshanzel** [comment] 2024-11-15 23:15
@mihai-ro I'm investigating the case now; I'll get back to you once I've found the root cause. Don't worry; we will restore your streak if it is deemed to have been kept.

**Comment by sshanzel** [comment] 2024-11-20 10:46
@mihai-ro I've now recovered your streak to its rightful amount 🙏 

We've merged a fix on the issue you raised about being unable to recover. We'll continue monitoring to see that things are working as intended.

**Closed by sshanzel** 2024-11-20 10:46 UTC
Labels: Status: Accepted, Type: Bug
