### ISSUE TITLE
🐛 BUG: Web Feed not rendering/loading

### ISSUE THREAD

**Issue by whoop-t** [dailydotdev/daily#1390] opened 2024-09-02 01:20 UTC
### What went wrong? 🤔

All feeds and explore popular are not rendering on web daily dev.

Tested Chrome and incognito, Edge

### Expected Behavior

Feeds rending

### Steps to Reproduce Issue

```bash
1. Login
2. No Feed displayed for my user
```

### Screenshots

[Blank feed](https://imgur.com/a/lY9YaMT)

[logs](https://imgur.com/a/gCr2woP)

### Environment

Windows 10, Chrome

### Browsers

Chrome, Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-09-02 04:55
Closing as duplicate of https://github.com/dailydotdev/daily/issues/1392
Keeping all discussion there.

**Closed by rebelchris** 2024-09-02 04:55 UTC
Labels: Type: Bug
