### ISSUE TITLE
Time Spent Alert

### ISSUE THREAD

**Issue by keshavashiya** [dailydotdev/daily#519] opened 2022-04-11 18:11 UTC
Hi Team,

Can we have **`Time Spent Alert`** so we've been notified if we're spending more time on it, since while reading blogs we forgot to get back to work and this leads to miss deadlines.

Thanks

_Originally posted by @keshavashiya in https://github.com/dailydotdev/daily/discussions/518_

**Comment by idoshamun** [comment] 2022-04-12 04:46
Closing as it's a duplicate of https://github.com/dailydotdev/daily/discussions/518

**Closed by idoshamun** 2022-04-12 04:46 UTC
