### ISSUE TITLE
🐛 BUG: There is something wrong with how Streaks are calculated.

### ISSUE THREAD

**Issue by Zonalds** [dailydotdev/daily#1501] opened 2024-10-15 04:22 UTC
### What went wrong? 🤔

I am logged in daily - including weekends, and pretty much read an article daily but every 10 days or so I get a message that streak ended. 

### Steps to Reproduce Issue

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by rebelchris** [comment] 2024-10-15 04:26
Hi @Zonalds would you mind sending your userID here this way we can verify what's happening on your account.

You can find it by visiting the following URL:

https://api.daily.dev/id

**Comment by mfurqanliaqat** [comment] 2024-11-02 15:40
I also faced this yesterday, my streak of 51 days is ended no reason :(

userID: SwGGVJIKRN0eM1pgLnBFH

**Comment by rebelchris** [comment] 2024-11-04 06:29
@mfurqanliaqat You didn't read on the 27th according to our metrics.
You would have been given the chance to recover the streak the next day though, did you end up doing that?

**Comment by mfurqanliaqat** [comment] 2024-11-04 06:31
Of course I did, also it ended on 30th and not on 27. I was active these days and also read articles... And something weird happened on Saturday Nov 2. I did read 5-10 articles. Only for the streak to sometimes show to 2 and sometimes back again to 1.... It's weird

**Comment by rebelchris** [comment] 2024-11-04 07:29
You also missed reading on Friday 1st of November.
Can you confirm this timezone is correct for you: `Asia/Tashkent`?

**Comment by mfurqanliaqat** [comment] 2024-11-04 08:18
I did not miss on Friday, on Friday it said same that 51 day streak is broken as it said before pretty strange. and I also did on 2, 3 and even today the streak is still 1, today morning. now it is 2. Same as it happened yesterday and the day before since 30th Oct. My timezone is Germany

**Comment by rebelchris** [comment] 2024-11-04 08:34
So the issue is that you set your timezone to a wrong one, which causes you to loose your streak.
You can set it to the correct one here, which will solve your issues:
https://app.daily.dev/account/notifications

**Comment by rebelchris** [comment] 2024-12-03 06:46
We are aware of some issue with our streak, closing this in favor of keeping all comms in #1619

**Closed by rebelchris** 2024-12-03 06:46 UTC
Labels: Status: Accepted, Type: Bug
