### ISSUE TITLE
🐛 BUG: Continually asked, "Where did you hear about us?"

### ISSUE THREAD

**Issue by ilittlewood** [dailydotdev/daily#1183] opened 2024-05-28 15:14 UTC
### What went wrong? 🤔

Every time I visit the web version of Daily Dev, one panel prompts me to answer, "Where did you hear about us?" - once should be enough.

### Expected Behavior

Question should only be asked (and answered) ONCE.

### Steps to Reproduce Issue

```bash
1. Go to website
2. Notice the panel with the "How did you hear about us?" question
```

### Solution Proposed

Ask the question once, store the answer, don't ask again.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

Windows 11, Edge browser (125.0.2535.51)

### Browsers

Microsoft Edge

### OS

Windows

### Code of Conduct

- [X] I follow the conditions of this project.

**Comment by idoshamun** [comment] 2024-05-28 15:53
Hi @ilittlewood,

You're right! It's definitely a bug.
Can you share reproducible steps please?
Do you use the extension or the webapp?

**Comment by ilittlewood** [comment] 2024-05-29 02:03
I'm using the webapp - I noticed the URL that I had saved was, "https://app.daily.dev/?ua=true" - once I noticed this, I tried, "https://app.daily.dev/?ua=false" and simply, "https://app.daily.dev/" and neither of these URLs  yielded the question - this may be a non-issue after all.

**Comment by idoshamun** [comment] 2024-05-29 05:28
Yes we currently use this flag to decide if we should the card, saving the url with this flag means it will show forever. we will think if we can come up with another logic but since you managed to solve the issue I'm closing the issue

**Closed by idoshamun** 2024-05-29 05:28 UTC
Labels: Type: Bug
